server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost}:5432/shopping_cart
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

jwt:
  secret: ${JWT_SECRET:acPmic02z6BK4fzVhqjPIYuKFq5+o8eOQw2iZVVnLLM=}
  expiration: 86400000 # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha