server:
  port: 8082

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  application:
    name: product-service

external:
  api:
    url: https://fakestoreapi.com

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      fake-store-api:
        connectTimeout: 3000
        readTimeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha